version: '3'

services:
  api:
    container_name: challenge-api
    build:
      context: .
    ports:
      - 3000:8080
    environment:
      - SERVICE_A_BASE_URL=http://integration:5000
      - SERVICE_B_BASE_URL=http://integration:5000
      - SERVICE_B_BASE_URL=http://integration:5000
  integration:
    container_name: challenge-integration
    image: zanfranceschi/desafio-01-cotacoes
    ports:
      - 5000:80